"""Schemas package for the Design Service.

This module contains all Pydantic schemas for request/response models,
including base schemas, design schemas, layout schemas, shading schemas, and BOM schemas.
"""

# Base schemas
from .base import (
    BaseResponse,
    ErrorResponse,
    ListResponse,
    PaginatedResponse,
    SuccessResponse,
    TimestampSchema,
    UUIDSchema,
)

# Design schemas
from .design import (
    DesignApprovalCreate,
    DesignApprovalResponse,
    DesignApprovalUpdate,
    DesignAttachmentCreate,
    DesignAttachmentResponse,
    DesignCommentCreate,
    DesignCommentResponse,
    DesignCommentUpdate,
    DesignCreate,
    DesignResponse,
    DesignShareCreate,
    DesignShareResponse,
    DesignShareUpdate,
    DesignTagCreate,
    DesignTagResponse,
    DesignUpdate,
    DesignVersionCreate,
    DesignVersionResponse,
)

# Layout schemas
from .layout import (
    LayoutConstraintCreate,
    LayoutConstraintResponse,
    LayoutConstraintUpdate,
    LayoutCreate,
    LayoutModuleCreate,
    LayoutModuleResponse,
    LayoutModuleUpdate,
    LayoutOptimizationCreate,
    LayoutOptimizationResponse,
    LayoutResponse,
    LayoutTemplateCreate,
    LayoutTemplateResponse,
    LayoutTemplateUpdate,
    LayoutUpdate,
    LayoutZoneCreate,
    LayoutZoneResponse,
    LayoutZoneUpdate,
)

# Shading schemas
from .shading import (
    ShadingAnalysisCreate,
    ShadingAnalysisResponse,
    ShadingAnalysisUpdate,
    ShadingMitigationCreate,
    ShadingMitigationResponse,
    ShadingMitigationUpdate,
    ShadingObjectCreate,
    ShadingObjectResponse,
    ShadingObjectUpdate,
    ShadingReportCreate,
    ShadingReportResponse,
    ShadingResultResponse,
    ShadingVisualizationCreate,
    ShadingVisualizationResponse,
)

# BOM schemas
from .bom import (
    BOMCostAnalysisCreate,
    BOMCostAnalysisResponse,
    BOMCreate,
    BOMItemCreate,
    BOMItemResponse,
    BOMItemUpdate,
    BOMResponse,
    BOMTemplateCreate,
    BOMTemplateResponse,
    BOMTemplateUpdate,
    BOMUpdate,
    ComponentCreate,
    ComponentResponse,
    ComponentUpdate,
)

__all__ = [
    # Base schemas
    "BaseResponse",
    "ErrorResponse",
    "ListResponse",
    "PaginatedResponse",
    "SuccessResponse",
    "TimestampSchema",
    "UUIDSchema",
    # Design schemas
    "DesignCreate",
    "DesignResponse",
    "DesignUpdate",
    "DesignVersionCreate",
    "DesignVersionResponse",
    "DesignApprovalCreate",
    "DesignApprovalResponse",
    "DesignApprovalUpdate",
    "DesignCommentCreate",
    "DesignCommentResponse",
    "DesignCommentUpdate",
    "DesignAttachmentCreate",
    "DesignAttachmentResponse",
    "DesignTagCreate",
    "DesignTagResponse",
    "DesignShareCreate",
    "DesignShareResponse",
    "DesignShareUpdate",
    # Layout schemas
    "LayoutCreate",
    "LayoutResponse",
    "LayoutUpdate",
    "LayoutZoneCreate",
    "LayoutZoneResponse",
    "LayoutZoneUpdate",
    "LayoutModuleCreate",
    "LayoutModuleResponse",
    "LayoutModuleUpdate",
    "LayoutOptimizationCreate",
    "LayoutOptimizationResponse",
    "LayoutTemplateCreate",
    "LayoutTemplateResponse",
    "LayoutTemplateUpdate",
    "LayoutConstraintCreate",
    "LayoutConstraintResponse",
    "LayoutConstraintUpdate",
    # Shading schemas
    "ShadingAnalysisCreate",
    "ShadingAnalysisResponse",
    "ShadingAnalysisUpdate",
    "ShadingObjectCreate",
    "ShadingObjectResponse",
    "ShadingObjectUpdate",
    "ShadingResultResponse",
    "ShadingMitigationCreate",
    "ShadingMitigationResponse",
    "ShadingMitigationUpdate",
    "ShadingReportCreate",
    "ShadingReportResponse",
    "ShadingVisualizationCreate",
    "ShadingVisualizationResponse",
    # BOM schemas
    "BOMCreate",
    "BOMResponse",
    "BOMUpdate",
    "BOMItemCreate",
    "BOMItemResponse",
    "BOMItemUpdate",
    "ComponentCreate",
    "ComponentResponse",
    "ComponentUpdate",
    "BOMTemplateCreate",
    "BOMTemplateResponse",
    "BOMTemplateUpdate",
    "BOMCostAnalysisCreate",
    "BOMCostAnalysisResponse",
]